export enum ResponseMessage {
    EXAMPLE_GET = "List of examples fetched successful.",
    EXAMPLE_GET_ID = "Example by id fetched successful.",
    EXAMPLE_POST = "Example created successful.",
    EXAMPLE_PATCH = "Example updated successful",
    EXAMPLE_DELETE = "Example deleted successful",
    EXAMPLE_VISIBILITY = "Example visibility updated successful",
    
    TEST_GET = "List of tests fetched successful.",
    TEST_GET_ID = "Test by id fetched successful.",
    TEST_POST = "Test created successful.",
    TEST_PATCH = "Test updated successful",
    TEST_DELETE = "Test deleted successful",
    TEST_VISIBILITY = "Test visibility updated successful",

    BOOK_GET = "List of books fetched successful.",
    BOOK_GET_ID = "Book by id fetched successful.",
    BOOK_POST = "Book created successful.",
    BOOK_PATCH = "Book updated successful",
    BOOK_DELETE = "Book deleted successful",
    BOOK_VISIBILITY = "Book visibility updated successful",

    VIDEO_GET = "List of videos fetched successful.",
    VIDEO_GET_ID = "Video by id fetched successful.",
    VIDEO_POST = "Video created successful.",
    VIDEO_PATCH = "Video updated successful",
    VIDEO_DELETE = "Video deleted successful",
    VIDEO_VISIBILITY = "Video visibility updated successful",

    ADMIN_LOGIN = "Admin logged in successfully",
    ADMIN_PROFILE = "Admin profile get suceessfully",
    ADMIN_GET = "List of admins fetched successful.",
    ADMIN_GET_ID = "Admin by id fetched successful.",
    ADMIN_POST = "Admin created successful.",
    ADMIN_PATCH = "Admin updated successful",
    ADMIN_DELETE = "Admin deleted successful",
}